### ISSUE TITLE
Image icon for Jenkins is missing

### ISSUE THREAD

**Issue by DHaussermann** [waseem18/mattermost-plugin-jenkins#5]
When using the plugin on a test server (version `0.2.0`) I see a broken image.
![MissingJenkinsImage](https://user-images.githubusercontent.com/35588783/57899850-9bd78e00-782c-11e9-9fb6-b7c6161f2dfd.PNG)

It's trying to serve me an image located here:  [server URL]_/plugins/jenkins/assets/jenkins.png_ but the image is not available.

Seems possible there may be a permissions issue with the server but, please see if you can repo this on a different Mattermost server.

**Comment by waseem18** [comment]
I'll take a dig at this today @DHaussermann
